server:
  port: 9090

spring:
  application:
    name: ${side-app-name}

ms-source-generic:
  port: ${port:3000}
  health-uri: http://localhost:${ms-source-generic.port}/${health-uri:health.json}
  home-page-uri: http://localhost:${ms-source-generic.port}/
